### PR TITLE
Docker images for the manager and gateway components.

### PR DESCRIPTION
**Pull request by bogdanmic**
The idea is to create more production ready images for Apiman by separating the Manager and Gateway components.

### CODE REVIEW

**Comment by EricWittmann** [comment]
There are a lot of files and references with specific Apiman version numbers in them.  Can you briefly describe the strategy on these images?  I'm thinking it would be better to have a more generic approach so that when we do releases, these images aren't pinned to older versions.  If we **need** the versions in there for some reason, then perhaps we can update the release script to automatically adjust things as appropriate whenever a release is performed.  And then tag and release this repo as well.

**Comment by bogdanmic** [comment]
The images were build based on the [on-wildfly11](https://github.com/apiman/apiman-docker/tree/master/on-wildfly11) image
The reasoning behind the images is as follows:
1. First we need the APIMAN_VERSION  like in the official builds. In this case: 1.5.5.Final
2. Remove all unnecessary files that I noticed are not needed for the **manager** or for the **gateway**. Like external dependencies, for instance: keycloak and elasticsearch.  I might have missed a few.
3. Based on the original files that were found in the **apiman-distro-wildfly11-$APIMAN_VERSION-overlay.zip**, i made a copy of those and then adjusted them to receive environment variables as configurations. And I also removed unneeded configurations. Because those files might differ from version to version I decided to create a copy  for each version available. This step could be removed if the original configs would allow this,  or if i would have figured it out.
4. I've added a readme file to explain the available configurations.
5. Then added a docker-compose.yml file as an usage example.

Ideally all these config adjustments should be handled when the app is built. I know that for the sake of simplicity of testing the product it's easy to  bundle everything together but from a production standpoint probably you would want to manage the keycloack and elasticsearch separately. 
If the build pipeline could produce two bundles, one for the manager and one for the gateway that should make things a lot easier in the future. And maybe even easier to develop and maintain as long as the contract between the components is maintained.

I hope this explanation helps.

**Comment by EricWittmann** [comment]
Thank you for the explanation - that is very helpful indeed.  I'll have to think about what the best thing is going forward.  I definitely agree with the goal of splitting up the components into separate docker images, and also with managing the other bits (DB, keycloak, elasticsearch) separately.  I just need to make sure that the approach we take is sustainable (ie automated).  :)

**Comment by bogdanmic** [comment]
Cool. Let me know if there are any other questions or changes needed.

**Comment by msavy** [comment]
@bogdanmic somehow I missed this, sorry!

This is a really awesome contribution. At some point in the near future (might not be this release, but probably one soon), we'll start doing docker-compose distributions with each part separated out in a much more 'production-ready' way.

We will merge in some of your excellent ideas and work into that.

**Comment by volkflo** [comment]
@bogdanmic I started with PR-41 and made you Co-Author because we used some of your ideas as well.

**Comment by bogdanmic** [comment]
Hi guys,
Sorry. I've seen your comments only now 😢 
I guess they got lost through other notifications from work.
I assume I can close this PR now.

**Comment by msavy** [comment]
Thanks very much for your assistance @bogdanmic - will close this now as I think we've integrated all your work

**Pull request closed without merging**
